add test vector for shared-stated retry service
quicwg/load-balancers pull request #117
Opened 2021-04-29 07:08 UTC by william-zk

see issue: #114

2021-05-05 19:36 UTC, martinduke commented on draft-ietf-quic-load-balancers.md
> +## Share-state Retry Token
```suggestion
## Shared-state Retry Token
```

2021-05-05 20:56 UTC, martinduke commented on draft-ietf-quic-load-balancers.md
> +AEAD_associated_data 0x0100007f000000000000000000000000cc9d8ecc83cfba681ec5d0ac00
The IP address is backwards. It should appear as it does it does in the IP header: 7f000001.

2021-05-05 21:46 UTC, martinduke requested changes
When I fake my inputs to use the inverted IP address as you have here, I get the same output. So I think your code is sound except for that.

2021-05-11 03:36 UTC, william-zk commented
> When I fake my inputs to use the inverted IP address as you have here, I get the same output. So I think your code is sound except for that.

Sounds great, I have rewrite the test-vector and give more information about it,please confirm again if you are free

2021-05-14 20:36 UTC, martinduke approved these changes
Checks out, thanks

2021-05-14 20:37 UTC, merged